SOURCE=chartype.cpp  mlmamain.cpp  ../../xmorph/capsheme.cpp  ../../xmorph/lemmatiz.cpp  ../../xmorph/wildscan.cpp ../dictree/classmap.cpp  ../dictree/flexTree.cpp  ../dictree/lidstree.cpp  ../dictree/mixTypes.cpp  ../dictree/mxTables.cpp  ../dictree/stemtree.cpp
TARGET=LIB
OBJDIR=../../tmp/rus/libdict/
OUTPUT=../../lib/libmorphrus$(_LIB)
INCLUDE=./ ../../ ../../../

include ../../build/maketools.gmake
