environment:
  matrix:
    - CMAKE_BUILD_TYPE: DEBUG
    - CMAKE_BUILD_TYPE: RELEASE

os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

init:
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%

before_build:
  - cmd: cmake -B. -H.

build_script:
  - cmake --build . --config %CMAKE_BUILD_TYPE%
